//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample02.Models.DomainModels.DTO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person5
    {
        public int Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string TelNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Addresss { get; set; }
        public string Email { get; set; }
    }
}
